// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZI0uaVK7YfM3Il-D1ArQ2izvPYeyY7cI',
    appId: '1:50513589242:web:a7098bba38a7da21b0ea43',
    messagingSenderId: '50513589242',
    projectId: 'iti-traning',
    authDomain: 'iti-traning.firebaseapp.com',
    storageBucket: 'iti-traning.appspot.com',
    measurementId: 'G-JVX1RJKQY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlRWIEShcyIYPeAx2UD21rKKLhaaG8PA',
    appId: '1:50513589242:android:91282b21e5dee40cb0ea43',
    messagingSenderId: '50513589242',
    projectId: 'iti-traning',
    storageBucket: 'iti-traning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2A8lik39TZCPsAxIZ50hH_Xoi_WWheo',
    appId: '1:50513589242:ios:e34513bf691045ebb0ea43',
    messagingSenderId: '50513589242',
    projectId: 'iti-traning',
    storageBucket: 'iti-traning.appspot.com',
    iosClientId: '50513589242-ukgmdh0de83b7e1tjp0v804dnfipv3p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );
}
